### ISSUE TITLE
PHP Error Log full of lots of errors since update

### ISSUE THREAD

**Issue by NyssaTheHobbit** [codepotent/PHP-Error-Log-Viewer#12]
Both of my ClassicPress installations are spitting out the same error since the update:

Undefined index: reverse_sort in [redacted]/wp-content/plugins/codepotent-php-error-log-viewer/codepotent-php-error-log-viewer.php on line 446

**Comment by johnalarcon** [comment]
It must be the "0" that I initialized the value with on activation. Can you try clicking the `Apply Filters` button (to save the options) and let me know if that resolves the error? Thanks for reporting this and apologies for the inconvenience.

**Comment by johnalarcon** [comment]
No, that wasn't it. I pushed a quick patch in version 2.0.1. :)

**Comment by NyssaTheHobbit** [comment]
So far so good.  Thanks!
