### ISSUE TITLE
Show log file name near log size

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/PHP-Error-Log-Viewer#17]
# Description
It can be handy to see what is the actual log file, like this:
![image](https://user-images.githubusercontent.com/29772709/77228353-f6e1bc00-6b86-11ea-94d1-99c66d4a44a6.png)

# Context
While playing around it took to me much time to figure out that `wp-includes/load.php` is overriding the `ini_set('error_log', $error_log_file);` in my `wp-config.php`. Not a _PHP Error Log Viewer_ issue but this can help!

**Comment by johnalarcon** [comment]
This would be a nice addition. Can you verify that `ini_get('error_log')` returns the correct path to your error log?

**Comment by xxsimoxx** [comment]
Yes... it returns the currect path!

**Comment by johnalarcon** [comment]
Thanks. I'll get this in.

**Comment by johnalarcon** [comment]
This has been implemented on the [add-error-log-path](https://github.com/codepotent/PHP-Error-Log-Viewer/tree/add-error-log-path) branch.
