### ISSUE TITLE
Allow purging the error log from admin bar

### ISSUE THREAD

**Issue by johnalarcon** [codepotent/PHP-Error-Log-Viewer#22]
# Description
Currently, you must visit the actual error log page in order to purge the log. An option to purge the log directly from the admin bar should be offered, with a redirect back to the same page. It can be a submenu of the `PHP Errors` entry.

# Context
A few less clicks in a day.

**Comment by xxsimoxx** [comment]
I think that this can also solve a caching problem that prevents the "purge error log" button from work.
Doing it with AJAX would be better for me, so if you are working on a page you have not to save changes before clearing logs.

**Comment by johnalarcon** [comment]
I haven't come across the caching issue on this end.

Yeah, it would be more handy with AJAX. The issue is that it would cost more time than I have to spend on it – it would need the basic AJAX functionality, as well as additional JS to update error bubbles and the view. If I go with a traditional link, I can hook it into the existing purge listener (including handling the nonce and confirmation) with just a single line in the JS.

**Comment by johnalarcon** [comment]
So, I did end up going with an AJAX solution on this. Resolved in 2.2.0.
